### ISSUE TITLE
wallet.py not found error

### ISSUE THREAD

**Issue by knmurphy** [BirdBotASA/BirdBotWindows#2]
Hi! 👋🏻 😃 

Thanks for writing this cool software! I'm really excited to see the progress and that it's not locked down to one camera hardware. I'm really new to ML/AI but have really been enjoying having some hummingbird feeders in my backyard 🐦 Looking forward to seeing BirdBot in action. 

I'm running into a snag with getting things started. When I click the 'Real-Time Mode' button I get the following error in my Anaconda Prompt shell:
`Exception in Tkinter callback
Traceback (most recent call last):
  File "D:\miniconda2\envs\BirdBot\lib\tkinter\__init__.py", line 1892, in __call__
    return self.func(*args)
  File "BirdBotML.py", line 46, in RealTimeMode
    Wallet = open("B:\BirdBot\BirdKeras\TensorFlow2\yolov3\wallet.py", "w")
FileNotFoundError: [Errno 2] No such file or directory: 'B:\\BirdBot\\BirdKeras\\TensorFlow2\\yolov3\\wallet.py'`

Are there any instructions anywhere about what wallet.py should be? thanks for any ideas, this looks super cool!

**Comment by knmurphy** [comment]
Found a comment on YouTube that cleared it up. The fix is https://github.com/BirdBotASA/BirdBotSoftware/commit/f987b5ad9ab29ec9d281b5f8f318877594bc634b

that got me past the error 👍🏻
